# Generated by Django 4.2.4 on 2023-08-14 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("raw_data", models.JSONField()),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="strava.athlete"
                    ),
                ),
            ],
        ),
    ]
